/**
 * ITradeSignal Interface
 * Represents a trading signal generated by the Strategy Engine
 */

export type TradeAction = 'BUY_YES' | 'BUY_NO' | 'SELL_YES' | 'SELL_NO';
export type SignalUrgency = 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';

export interface ITradeSignalMetadata {
  /** Current arbitrage spread when signal was generated */
  spread: number;
  /** YES price at signal generation */
  yesPrice: number;
  /** NO price at signal generation */
  noPrice: number;
  /** Strategy that generated this signal */
  strategyId: string;
  /** Reason for the trade signal */
  reason: string;
  /** Order book depth available at target price */
  availableDepth: number;
}

export interface ITradeSignal {
  /** Unique signal identifier (UUID) */
  signalId: string;
  /** Market this signal applies to */
  marketId: string;
  /** When the signal was generated (Unix ms) */
  timestamp: number;
  /** Trade action to execute */
  action: TradeAction;
  /** Target execution price */
  price: number;
  /** Position size in tokens */
  size: number;
  /** Signal confidence score (0-1) */
  confidence: number;
  /** Expected profit in USDC */
  expectedProfit: number;
  /** Maximum acceptable slippage (0-1) */
  maxSlippage: number;
  /** Execution urgency - determines queue priority */
  urgency: SignalUrgency;
  /** Time-to-live in milliseconds, signal expires after */
  ttlMs: number;
  /** Additional context for the signal */
  metadata: ITradeSignalMetadata;
}

/**
 * Factory function to create a trade signal
 */
export function createTradeSignal(
  params: Omit<ITradeSignal, 'signalId' | 'timestamp' | 'ttlMs'> & {
    ttlMs?: number;
  }
): ITradeSignal {
  return {
    signalId: crypto.randomUUID(),
    timestamp: Date.now(),
    ttlMs: params.ttlMs ?? 5000, // Default 5 second TTL
    ...params,
  };
}

/**
 * Check if a signal has expired
 */
export function isSignalExpired(signal: ITradeSignal): boolean {
  return Date.now() > signal.timestamp + signal.ttlMs;
}
